name       : foomatic-db-engine
version    : 4.0.13
release    : 10
source     :
    - https://www.openprinting.org/download/foomatic/foomatic-db-engine-4.0.13.tar.gz : b5c89027aa26967d2e6db62e2af7db0c4039d2480d4fbf2476a6ddcf609a5faf
license    : GPL-2.0-or-later
summary    : Foomatic database engine
component  : desktop.core
description: |
    Foomatic's database engine generates PPD files from the data in Foomatic's XML database. It also contains scripts to directly configure print queues and handle jobs.
rundeps    :
    - foomatic-db
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
