name       : foomatic-db-engine
version    : 4.0.12
release    : 3
source     :
    - http://www.openprinting.org/download/foomatic/foomatic-db-engine-4.0.12.tar.gz : 66143b76ed5b325b7025e261ad917b543de534c6d0a6e495d5489a20cace7c21
license    : GPL-2.0
summary    : Foomatic database engine
component  : desktop.core
description: |
    Foomatic's database engine generates PPD files from the data in Foomatic's XML database. It also contains scripts to directly configure print queues and handle jobs.
rundeps    :
    - foomatic-db
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
